### ISSUE TITLE
Adding support for TimeSeries

### ISSUE THREAD

**Issue by shivchawla** [dysonance/Indicators.jl#6]
Do you think it's good idea to add support for TimeSeries (in addition to TS)? I am using TimeSeries and I want to use this library directly with TimeSeries.

**Comment by JTAmos** [comment]
Hi @shivchawla, thanks for the recommendation. I definitely would not be opposed to adding that functionality. Since I am the author of [`Temporal`](https://github.com/dysonance/Temporal.jl), I am obviously more familiar with how that works, but could spend some time working on TimeSeries if you think it would be helpful.

As a short-term workaround, since Indicators.jl works with `Array`s, one thing you could do is extract the values component from the TimeSeries object, run the function you want on that `Array`, and place the result of that calculation into a TimeSeries object.

Also, if you'd like to help out with with a contribution that adds this functionality, feel free to fork this repo, write a prototype of the implementation, and open a pull request. I would be happy to review and add to the package if it looks good :)

**Comment by JTAmos** [comment]
@shivchawla, as an unrelated aside, may I ask what about the TimeSeries package you prefer over Temporal's `TS` type? I only ask because it would be good to have feedback on that package as well to see if there's something about it that is less user-friendly that I could address to make it better.

I actually started that project because I personally didn't care too much for how the TimeSeries type was designed (my background is using the [`xts`](http://joshuaulrich.github.io/xts/) R package which had functionality I felt TimeSeries was lacking).

Either way, still not opposed to working on this issue, but would be great to have a better idea of how to improve the [Temporal](https://github.com/dysonance/Temporal.jl) package.

**Comment by shivchawla** [comment]
@dysonance I don't really have an opinion on TS. I see the difference with TimeSeries but when I started out my work I didn't find TS. I read the discussion on merging TS and TimeSeries but don't know where that discussion currently stands right. 

You are right that I can use the array values to compute indicators but I just realized that it can only compute one series at a time. Don't you think that it should be modified to accept n-dimensional array as well. Anyway, I will see if I want to go ahead with MarketTechnicals or Indicators to minimize my work

Thanks for your input!

**Comment by JTAmos** [comment]
@shivchawla Appreciate the feedback. Could you provide an example/explanation of what you're trying to do? Then I can try to provide some example code of how it should work. My guess based on the n-dimensional array issue you mention is that when the values come out of TimeSeries the `Array` is not 1-dimensional, and since some of the functions require `Vector` type (basically an alias for `Array{T,1}`) they trip up with `Array{T,2}`.

If that's the case, then there would just need to be another indexing step, like `TimeSeriesObject.values[:,1]` to get a 1-dimensional array for a function like `sma` or the like. If I'm not on the right track, again, feel free to post an example of what you're doing and I can try to help out.

That being said, you do make a potentially good point, which is to make functions that take `Vector` type as the main argument also take `Array{T,2}` type and just compute the same function for each column. The reason I only did the `Vector` method is to avoid possible confusion ambiguity with other functions that *require* multiple columns to work (e.g. `adx`). If you think it would be better to generalize these methods and that this ambiguity isn't a big risk, that's a pretty straightforward change I think.

**Comment by JTAmos** [comment]
Closing as stale and outside scope of project. Further, support for TimeSeries should be possible by passing underlying arrays and writing wrapper methods.
